### ISSUE TITLE
Audio source is missing when sunball is triggered

### ISSUE THREAD

**Issue by ARTBankManager** [spcover/UnityrollingVR#10]
A component missing error happens when sunball is triggered, at line 77 of StartBall.cs.

**Comment by hfzhg** [comment]
Ah, thanks! Will add the audio source in the next commit.

**Comment by spcover** [comment]
Thanks for reporting! Will add audio source in the next commit.

**Comment by spcover** [comment]
Fixed in 1b0f04613809310c03c28ede7c3a1f436469b245
