### ISSUE TITLE
An array out of index error happens when interacting with all balls

### ISSUE THREAD

**Issue by ARTBankManager** [spcover/UnityrollingVR#9]
The error is reproducible and seems to be related to an under-sized array "string[] trace = new string[balls.Length];" at line 12 of Startball.cs

**Comment by hfzhg** [comment]
Can you send a stack trace or screenshot?

**Comment by spcover** [comment]
Fixed with f2d0ab0db847a35c8cda9ee637c56969a4b8d6e8
